services:
  rest-proxy:
    image: ts/reporting/rest-proxy:development
    container_name: ts_reporting_rest-proxy
    build: 
      context: .
      dockerfile: rest_proxy/Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    working_dir: /code/rest_proxy
    entrypoint: fastapi dev main.py
    command: --host 0.0.0.0 --port 8000
