services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  report_service:
    build: ./report_service/.
    ports:
      - "50051:50051"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NAME=report_service
    volumes:
      - ./report_service:/app

  frontend-fake-portal:
    container_name: frontend-fake-portal
    build: ./frontend/fake-unified-portal/.
    ports:
      - "3000:3000"
    volumes:
      - "./src:/app/frontend/fake-unified-portal/src"
      - "./package.json:/app/frontend/fake-unified-portal/package.json"
    command: "npm start"

  rest-proxy:
    image: ts/reporting/rest-proxy:development
    container_name: ts_reporting_rest-proxy
    build:
      context: .
      dockerfile: rest_proxy/Dockerfile
      target: development
    ports:
      - 8000:8000
    environment:
      - GRPC_SERVER=report_service:50051
    volumes:
      - ./rest_proxy/:/code/rest_proxy/
    working_dir: /code/rest_proxy
    entrypoint: fastapi dev main.py
    command: --host 0.0.0.0 --port 8000
    depends_on:
      - report_service

volumes:
  redis_data:
  report_service:
