apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-10-18T21:07:11Z"
  labels:
    app: report-service-frontend
  name: report-service-frontend
  namespace: default
  resourceVersion: "58879"
  uid: 7449acba-36c5-42ac-a394-81ac92ed0a0f
spec:
  clusterIP: 10.97.66.186
  clusterIPs:
  - 10.97.66.186
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30869
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: report-service-frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
