apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-10-18T21:36:10Z"
  labels:
    app: report-service-frontend
  name: report-service-frontend
  namespace: default
  resourceVersion: "61287"
  uid: ef22694f-9559-4e08-a3e7-48815475c790
spec:
  clusterIP: 10.101.81.19
  clusterIPs:
  - 10.101.81.19
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30280
    port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: report-service-frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
